exclude: '.pixi/'
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
  hooks:
    - id: check-yaml
    - id: check-toml
      exclude: "{{cookiecutter.package_name}}/pyproject.toml"
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: local
  hooks:
  - id: ruff
    name: ruff-format
    stages: [commit, push]
    language: system
    entry: pixi run fmt
    types: [python]
    pass_filenames: false

  - id: ruff
    name: ruff-check
    stages: [commit, push]
    language: system
    entry: pixi run lint
    types: [python]
    pass_filenames: false

  - id: Mypy
    name: mypy
    stages: [commit, push]
    language: system
    entry: pixi run types
    types: [python]
    pass_filenames: false

  - id: pytest
    name: pytest
    stages: [commit, push]
    language: system
    entry: pixi run test
    types: [python]
    pass_filenames: false
